### ISSUE TITLE
Inconsistent PDG list

### ISSUE THREAD

**Issue by NGoetz** [smash-transport/sparkx#108]
SMASH and SPARKX PDG lists are inconsistent. In SMASH, PDGs like "9922214" do appear, which SPARKX' PDG list does not know. Therefore, it cannot be removed from OSCAR objects.

**Comment by NGoetz** [comment]
We agreed to following changes:

- checking if the pdg id is valid is only done in Particle, at creation and when the pdg id is changed. it has to be removed from OSCAR and Jetscape
- At this point. a flag is set if the pdg id is valid or not
- If it is invalid, all  quantities deduced from pdg id are set to false. This has do be documented!

**Comment by Hendrik1704** [comment]
This is done now.
