### ISSUE TITLE
Histogram class

### ISSUE THREAD

**Issue by Hendrik1704** [smash-transport/sparkx#11]
Combine the two existing classes.

**Comment by Hendrik1704** [comment]
We need:
- Variable bin widths
- get_bin_centers()
- weighted average
- raw_counts as member variable
- set own errors

**Comment by nilssass** [comment]
Add mathod that sums over given number of histograms

**Comment by Hendrik1704** [comment]
Make the error a warning (only once) if some value is outside the bin ranges of the histogram.

**Comment by Hendrik1704** [comment]
Reminder: extend the print_to_file function to handle multiple histograms

**Comment by nilssass** [comment]
Done
