### ISSUE TITLE
Action to create new version on pypi

### ISSUE THREAD

**Issue by nilssass** [smash-transport/sparkx#114]
We need a github action that automatically publishes a new version on pypi with every new tag

**Comment by Hendrik1704** [comment]
This is something we should try to find out rather quick. The last times we did the release process I always did some thing wrong in the build process. It's probably easier to automatize this with an action. Here is a [https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/](link) to a website describing the process. I must confess that I did not understand the things stated there completely. These actions are kind of black magic to me...

**Comment by NGoetz** [comment]
This is something which afaik only the person can do who owns the pypi account this was published under. I think this is @Hendrik1704

**Comment by Hendrik1704** [comment]
This is merged now. Maybe the action will be triggered when we merge to main next week. Otherwise, we can do it by hand and fix this afterward.
