### ISSUE TITLE
Github action for documentation

### ISSUE THREAD

**Issue by NGoetz** [smash-transport/sparkx#118]
This is not working yet as intended.

**Comment by Hendrik1704** [comment]
@NGoetz @nilssass 
I had a discussion with Alessandro and we decided, that it is the cleanest way to use a development branch (`sparkx_devel`), where we push all the things to and then for the release / tag we push this branch to the main one. This way the documentation is only build once and is not ahead of the code.

This way we don't have to dive into the subtleties of GitHub actions...

What is your opinion on this?

**Comment by NGoetz** [comment]
I think this is the cleanest way to go anyway. It is always good to have a stable branch.

**Comment by Hendrik1704** [comment]
Ok, then we will go this way.
