### ISSUE TITLE
Zenodo id

### ISSUE THREAD

**Issue by NGoetz** [smash-transport/sparkx#119]
We should register this for an doi.

**Comment by Hendrik1704** [comment]
I logged into Zenodo with my ORCID and connected my GitHub account to the website. With the next release on GitHub there should be a Zenodo entry with DOI.

**Comment by Hendrik1704** [comment]
Yes, I guess it's because we have all the admin rights in the sparkx repo. The repo was the only one I was able to choose there. The ones from the other organizations where I'm a member had a red cross next to them.
