### ISSUE TITLE
Density smearing

### ISSUE THREAD

**Issue by NGoetz** [smash-transport/sparkx#120]
Add different options for density smearing in event characterisation.

**Comment by NGoetz** [comment]
The current implementation of density smearing struggles with particles at the edge of the lattice grid. We have decided to fix this by smearing the particles each on a separate grid with the same grid parameters, but smaller extent. This grid is then added at the correct position to the respective grid points inside the grid, therefore fixing the normalization also for edge particles and particles outside the grid.

**Comment by Hendrik1704** [comment]
This is done. Further development will be done if we hear something about the applicability in the hydro code.
