### ISSUE TITLE
Wrong physics when the particle is not known

### ISSUE THREAD

**Issue by Hendrik1704** [smash-transport/sparkx#143]
I just came across some functions in the Particle class and I'm not sure if we handle the new cases with `not self.pdg_valid_` correctly. See this function for example:
```
def is_meson(self):
        """
        Is the particle a meson?
        Returns
        -------
        bool
            True, False
        """
        if not self.pdg_valid_:
            return False
        return PDGID(self.pdg).is_meson
```
When you have an invalid particle for the `PDGID` package, this not-known particle is a highly excited meson. In this case, the function would give you `False` even if the particle is a meson. Shouldn't we return `None` in this case, when a statement about the physics of this particle is not possible?
With the given implementation the physics output might be wrong.

**Comment by NGoetz** [comment]
Are all not-known particles mesons? Otherwise, at this stage we just cannot for sure say what they are. We could of course return None, but then we would have to find a way how to deal with an undetermined case consistently.

**Comment by Hendrik1704** [comment]
No, not all unknown particles are mesons. This was just an example. I just wanted to say, that in case the particle would be a meson, then the output is `False` and so the physics is wrong.
We should have another output, which is given in cases where we can not make a statement and which is neutral in terms of physics, e.g. `None`.

**Comment by Hendrik1704** [comment]
I see your point. Then I will add a bit of explanation for this in the documentation. I'm currently adding `None` returns for all other functions like `spatial_rapidity`, if `t` or `z` is `None`. Otherwise, there are errors due to `Nones` in the members of the Particle class.

**Comment by NGoetz** [comment]
How about, when applying filtering, we treat `None` like `False`? That combines the best of both worlds.

**Comment by Hendrik1704** [comment]
That's also a good choice. Then I'll implement that.
