### ISSUE TITLE
Implement computation of multi particle transverse momentum correlations

### ISSUE THREAD

**Issue by Hendrik1704** [smash-transport/sparkx#156]
To study the initial state and nuclear structure, $[p_T]$ fluctuations can be used. This new article [arXiv:2312:00492](https://arxiv.org/pdf/2312.00492.pdf) provides a generic algorithm for the computation of multi-particle $[p_T]$ fluctuations.
With SPARKX we have the perfect tool to implement this new generic observable type quite easily.

**Comment by Hendrik1704** [comment]
This is the published version of this article: https://link.springer.com/article/10.1140/epja/s10050-024-01266-x

**Comment by Hendrik1704** [comment]
@NGoetz You can find the first implementation of the `MultiParticlePtCorrelations` class here: [roch/multiparticle_pt_fluct](https://github.com/smash-transport/sparkx/tree/roch/multiparticle_pt_fluct)

If you have time, you can go through the equations and compare them to the ones in the paper 😉.

The tests for the class are still missing, but I don't know how I can test the physics. I will for sure implement tests for errors and wrong input. Do you have an idea for the tests?

I also changed the order of the classes in the index of the documentation. It is now sorted in alphabetical order. This seems better for the future if people search for specific things.

**Comment by NGoetz** [comment]
Before I go through all the effort and check the coefficients - why did you not just implement eq 12 and 13, so that we have everything up to all orders?

Regarding tests, purely random particles should show very small correlations, and particles which are all aligned should show correlations to all orders, if I understand correctly?
