### ISSUE TITLE
Lee-Yang-Zero Flow: Ready for use

### ISSUE THREAD

**Issue by NGoetz** [smash-transport/sparkx#186]
I think the beta-test disclaimer can be removed - I double checked this class and PCA and it looks good. I would document though that if I create an LYZFlow object and use it to calculate an integrated flow from particle list 1, then I cannot just call differential flow on particle list 2, as some data is saved. This is a side effect not present in other flow classes.

**Comment by Hendrik1704** [comment]
This is done
