### ISSUE TITLE
Bug in weight of ReactionPlaneFlow class

### ISSUE THREAD

**Issue by Hendrik1704** [smash-transport/sparkx#194]
The weight in the ReactionPlaneFlow is wrong if the value is not set for a particle (e.g. from an OSCAR file). We changed the behavior in Particle to `nan` if a value is not set. Here we check for `None`.

https://github.com/smash-transport/sparkx/blob/9be1714aa39068a40ed9d5a7b872f62bb7e3cf3c/src/sparkx/flow/ReactionPlaneFlow.py#L92

https://github.com/smash-transport/sparkx/blob/9be1714aa39068a40ed9d5a7b872f62bb7e3cf3c/src/sparkx/flow/ReactionPlaneFlow.py#L157

We should check if this is the case in other places of the code.

**Comment by NGoetz** [comment]
This is fixed now.
