### ISSUE TITLE
More flexible histogram printout

### ISSUE THREAD

**Issue by NGoetz** [smash-transport/sparkx#195]
We should not enforce printing out systematic errors, especially if there are none. It should be only printed what is given as a header label.

**Comment by Hendrik1704** [comment]
The print of the histogram is supposed to have the same format as the hepdata table format. There, systematic errors are part of the format.

**Comment by NGoetz** [comment]
That makes a lot of sense but is not documented. Nevertheless, although HEPdata format is default, it should not be enforced.
