### ISSUE TITLE
Remove bins in histogram class

### ISSUE THREAD

**Issue by NGoetz** [smash-transport/sparkx#238]
Experimental data often has empty/non-measured bins. It would be nice to have discontinuous bin edges in the histogram class.

**Comment by Hendrik1704** [comment]
Can you produce this by creating a histogram with custom bins and then setting the weight for the bins you don't want to 0, while the others weigh 1?

**Comment by NGoetz** [comment]
Sure, but then I have still empty bins flying around. Ideally the internal arrays are shortened when I remove a bin.

**Comment by Hendrik1704** [comment]
Ah, OK. Now I get it 😄
