### ISSUE TITLE
QCumulant differential flow: POI PDG optional

### ISSUE THREAD

**Issue by NGoetz** [smash-transport/sparkx#240]
Due to line 776 in QCumulant-Flow, we enforce giving the pdg of POIs. However, the most common usecase is all charged particles. Therefore, this should be adapted.

**Comment by Hendrik1704** [comment]
Can't you just read in the data and filter for charged hadrons. Then you give this to the flow with the `poi_pdg=None`?

**Comment by NGoetz** [comment]
The problem was that `poi_pdg=None` caused a bug because `None` is not a list. Anyway, that was fixed by #242
