### ISSUE TITLE
Add Quickstart page

### ISSUE THREAD

**Issue by nilssass** [smash-transport/sparkx#272]
As the number of classes is increasing, it will be very hard for users to see where to begin, especially in our documentation.

I would suggest to add one documentation page after `Install` called `Quick Guide` where we briefly describe the usecases connected to each class in a meaningful hierarchy and give some super easy example. Maybe there is even a way to make this page downloadable or add a download button that will download the connected user guide as pdf

**Comment by Hendrik1704** [comment]
A first draft for the quickstart guide was implemented in #275. After the next updates of the development branch we should continue with this.
