### ISSUE TITLE
scale_histogram is broken

### ISSUE THREAD

**Issue by nilssass** [smash-transport/sparkx#315]
In scale_histogram(), line 922 we have:

```
elif isinstance(value, (list, np.ndarray)):
            if np.asarray(value).shape != self.histograms_[-1].shape:
                raise ValueError(
                    "The shape of the scaling factor array is not compatible with the histogram shape"
                )
self.histograms_[-1] *= np.asarray(value)
self.scaling_[-1] *= np.asarray(value)
self.error_[-1] *= np.asarray(value)
```

However, this is wrong. If value is a list in `self.error_[-1] *= np.asarray(value)` the last element of error_ (which is a number) will be multiplied by a list. 
This bug has never been caught, because we are missing a corresponding test which scales the histogram with a list of bin widths.

**Comment by Hendrik1704** [comment]
I can have a look at this.

**Comment by Hendrik1704** [comment]
I just went through the code pieces and I can not see what is wrong here in Histogram.py:
```
if isinstance(value, (int, float, np.number)):
  self.histograms_[-1] *= value
  self.scaling_[-1] *= value
  self.error_[-1] *= value

elif isinstance(value, (list, np.ndarray)):
  if np.asarray(value).shape != self.histograms_[-1].shape:
      raise ValueError(
          "The shape of the scaling factor array is not compatible with the histogram shape"
      )

  self.histograms_[-1] *= np.asarray(value)
  self.scaling_[-1] *= np.asarray(value)
  self.error_[-1] *= np.asarray(value)
```

We perform both versions of the scaling (with a single value and a list) in the tests:
```
def test_scale_histogram_single_factor():
    # Test scaling histogram with a single factor
    hist = Histogram((0, 10, 10))
    hist.add_value([1, 3, 5, 7, 9])
    hist.scale_histogram(2)
    assert np.allclose(
        hist.histogram(), np.array([0, 2, 0, 2, 0, 2, 0, 2, 0, 2])
    )


def test_scale_histogram_multiple_factors():
    # Test scaling histogram with multiple factors
    hist = Histogram((0, 10, 10))
    hist.add_value([1, 3, 5, 7, 9])
    hist.add_histogram()
    hist.add_value([2, 4, 6, 8, 9])
    with pytest.raises(ValueError):
        # Passing incorrect length of scaling list
        hist.scale_histogram([2, 0.5])
    hist.scale_histogram([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])
    assert np.allclose(
        hist.histogram(),
        np.array(
            [[0, 1, 0, 1, 0, 1, 0, 1, 0, 1], [0, 0, 2, 0, 2, 0, 2, 0, 2, 2]]
        ),
    )
```
@NGoetz Maybe you can also have a look at this. I don't really understand the issue...

**Comment by NGoetz** [comment]
So it seems to me that scaling the idea is that.

- We always scale the last histogram. This behaviour is as documented.
- If we scale with a value, we scale all bins equally.
- If we scale with an array, there has to be one and only one factor per bin.

Nils' error happens if error_ is a 1D array. That should not happen.

**Comment by nilssass** [comment]
This is really weird. This was the reason why the tests in BulkObservables are failing. If I comment out the line 
```
self.error_[-1] *= np.asarray(value)
```
everything (but the error calculation) works. The error message I get is: 
`ValueError: setting an array element with a sequence.`

**Comment by NGoetz** [comment]
What is the shape of error_., and why is it like that?
